gpush: publish current branch as master

diff --git a/bin/gpush b/bin/gpush
--- a/bin/gpush
+++ b/bin/gpush
@@ -13,8 +13,15 @@ fi
 
 PROJECTNAME=$(basename `pwd`)
 
-git push $@ git.alt:packages/$PROJECTNAME.git
-git push --tags git.alt:packages/$PROJECTNAME.git
+CURRENTBRANCH=$(git branch | grep "^\*" | cut -d " " -f 2)
+
+if [ -z "$CURRENTBRANCH" ] ; then
+	echo "Can't detect current branch"
+	exit 1
+fi
+
+git push $@ git.alt:packages/$PROJECTNAME.git $CURRENTBRANCH:master
+git push --tags git.alt:packages/$PROJECTNAME.git $CURRENTBRANCH:master
 
 #> $ git commit -a; A='0.23-alt1'; git tag -s $A; \
 #>   git tag -s -f -m 'Sisyphus release $A' sisyphus $A
