small sisyphus_check

diff --git a/bin/myhsh b/bin/myhsh
--- a/bin/myhsh
+++ b/bin/myhsh
@@ -106,9 +106,7 @@ fi
 
 # Skip checking for tar arg
 if [ -n "${LISTNAMES/*tar/}" ] ; then
-	echog -n "Checking with sisyphus_check (with $HASHER_NOCHECK skipping)... "
-	sisyphus_check --no-check=$HASHER_NOCHECK --files $LISTNAMES || fatal "check for sisyphus failed"
-	echog "OK"
+	docmd sisyphus_check --no-check=$HASHER_NOCHECK --files $LISTNAMES || fatal "check for sisyphus failed"
 fi
 
 # export OURAPTCONF with temp. file contains correct path to sources.list
diff --git a/bin/rpmbs b/bin/rpmbs
--- a/bin/rpmbs
+++ b/bin/rpmbs
@@ -338,15 +338,15 @@ fi
 ############################################
 echog "Changing permissions..."
 chmod 644 -- $LISTBUILT || fatal "can't chmod"
-echog -n "Checking with sisyphus_check..."
 
 # TODO: check for ALT specific
 # skip some checking for src.rpm if it is local upload
 CHECK_OPTIONS=""
 [ -n "${UPLOADNOW}" ] || CHECK_OPTIONS="--no-check=$HASHER_NOCHECK"
 
-test -n "$NOCHECK" || sisyphus_check $CHECK_OPTIONS --files $LISTBUILT || fatal "sisyphus check failed"
-echog "OK"
+if [ -z "$NOCHECK" ] ; then
+    docmd sisyphus_check $CHECK_OPTIONS --files $LISTBUILT || fatal "sisyphus check failed"
+fi
 
 # due rpm's find-req
 RPMLINT=rpmlint
