rpmbsh: fix install in hasher for backported packages

diff --git a/bin/rpmbsh b/bin/rpmbsh
--- a/bin/rpmbsh
+++ b/bin/rpmbsh
@@ -98,7 +98,7 @@ fi
 
 # if ok and requested test install, do it
 if [ "$RESULT" = "0" ] && [ -n "$INSTALLPKG" ] ; then
-	BINPACKAGES=$($ETERBUILDBIN/myhsh -b $LISTBUILT | estrlist reg_exclude debuginfo -) || fatal "Can't get binary packages for $LISTBUILT"
+	BINPACKAGES=$($ETERBUILDBIN/myhsh $MENVARG -b $LISTBUILT | estrlist reg_exclude debuginfo -) || fatal "Can't get binary packages for $LISTBUILT"
 
 	echo
 	echog "List of binary packages:"
