rpmbs: set project name to gpush

diff --git a/bin/rpmbs b/bin/rpmbs
--- a/bin/rpmbs
+++ b/bin/rpmbs
@@ -159,7 +159,7 @@ if [ -n "$UPLOADNOW" ] && is_gear $SPECDIR ; then
 	build_rpms_name "$LISTNAMES"
 	release_check
 	check_gear_and_tag
-	$ETERBUILDBIN/gpush || fatal "Git push via gpush failed. Possibly you need to run ginit for create remote repo."
+	$ETERBUILDBIN/gpush $BASENAME || fatal "Git push via gpush failed. Possibly you need to run ginit for create remote repo."
 	TAG=$VERSION-$RELEASE
 	if [ -n "$TASKNUMBER" ] ; then
 		ssh $GIRARHOST task add $TASKNUMBER repo $BASENAME $TAG
