change myhsh -b to myhsh -p

diff --git a/bin/rpmbsh b/bin/rpmbsh
--- a/bin/rpmbsh
+++ b/bin/rpmbsh
@@ -102,7 +102,7 @@ fi
 
 # if ok and test install is requested, do it
 if [ "$RESULT" = "0" ] && [ -n "$INSTALLPKG" ] ; then
-	BINPACKAGES=$($ETERBUILDBIN/myhsh $MENVARG -b $LISTBUILT | estrlist reg_exclude ".*debuginfo.*" -) || fatal "Can't get binary packages for $LISTBUILT"
+	BINPACKAGES=$($ETERBUILDBIN/myhsh $MENVARG -p $LISTBUILT | estrlist reg_exclude ".*debuginfo.*" -) || fatal "Can't get binary packages for $LISTBUILT"
 
 	estrlist isempty "$BINPACKAGES" && fatal "There is no binary packages after build"
 
