fix small bugs

diff --git a/bin/rpmbs b/bin/rpmbs
--- a/bin/rpmbs
+++ b/bin/rpmbs
@@ -255,7 +255,13 @@ if [ -n "$UPLOADNOW" ] && is_gear $SPECDIR ; then
 
 		PROJECTNAME=$(get_repo_name)
 
-		check_gear_and_tag || fatal "Can't make tag"
+		if ! check_gear_and_tag ; then
+			if [ "$PREPARETASK" = "internal" ] ; then
+				docmd ssh $GEARHOST task rm $TASKNUMBER
+			fi
+			fatal "Can't make tag"
+		fi
+
 		TAG=$(get_last_tag)
 
 		# TODO: add check for repo (as in rpmgp) and run ginit if needed
diff --git a/bin/rpmbsh b/bin/rpmbsh
--- a/bin/rpmbsh
+++ b/bin/rpmbsh
@@ -40,7 +40,7 @@ phelp()
 	echog "   -b REPONAME  binary repository name (4.1, p5, t6 and so on)"
 }
 
-while getopts :ihtb: opt; do
+while getopts :hitb: opt; do
     case $opt in
     h) phelp; exit 0;;
     t) COMMIT="--commit" ;;
@@ -86,9 +86,10 @@ pack_src_rpm $COMMIT $(drop_args "$LISTRPMARGS" s u c l f a A)
 
 # TODO: use gear --hasher directly, drop myhsh
 
-#if rhas "$LISTNAMES" spec ; then
-#	set_specdir $LISTNAMES
-#fi
+# use later for is_gear
+if rhas "$LISTNAMES" .spec ; then
+	set_specdir $LISTNAMES
+fi
 
 # build in hasher
 docmd time $ETERBUILDBIN/myhsh $MENVARG $(drop_args "$LISTRPMARGS" f u a A) $LISTBUILT
@@ -96,7 +97,7 @@ RESULT=$?
 
 # if ok and requested test install, do it
 if [ "$RESULT" = "0" ] && [ -n "$INSTALLPKG" ] ; then
-	BINPACKAGES=$($ETERBUILDBIN/myhsh -b $LISTBUILT) || fatal "Can't get binary packages for $LISTBUILT"
+	BINPACKAGES=$($ETERBUILDBIN/myhsh -b $LISTBUILT | estrlist reg_exclude debuginfo -) || fatal "Can't get binary packages for $LISTBUILT"
 
 	echo
 	echog "List of binary packages:"
@@ -113,7 +114,7 @@ fi
 
 # remove generated src.rpm
 for i in $LISTBUILT ; do
-	estrlist has $i $LISTNAMES || rm -f $i
+	estrlist has $i $LISTNAMES || rm -fv $i
 done
 
 date
