rpmbs: push branch too

diff --git a/bin/rpmbs b/bin/rpmbs
--- a/bin/rpmbs
+++ b/bin/rpmbs
@@ -212,6 +212,7 @@ if [ -n "$UPLOADNOW" ] && is_gear $SPECDIR ; then
 	TAG=$VERSION-$RELEASE
 	check_gear_and_tag "$TAG"  # || fatal "Can't make tag"
 	$ETERBUILDBIN/gpush $GIRARHOST $FORCE "$TAG" || fatal "gpush failed. Possibly you need to run ginit for create remote repo. Try \$ gpush $GIRARHOST $TAG command separately"
+	$ETERBUILDBIN/gpush $GIRARHOST $FORCE || fatal "gpush failed"
 	echo
 	echo "Run build $PROJECTNAME at $GIRARHOST"
 	if [ -n "$TASKNUMBER" ] ; then
