rpmbph: merge with master tag

diff --git a/bin/rpmbph b/bin/rpmbph
--- a/bin/rpmbph
+++ b/bin/rpmbph
@@ -108,6 +108,9 @@ if [ "$PKGVENDOR" = "alt" ] && is_gear $SPECDIR ; then
 		set_specdir $SPEC
 		docmd cd $SPECDIR || fatal
 
+		is_last_commit_tag || fatal "We allow backport only when last commit has (release) tag"
+		LASTTAG="$(get_last_tag)" || fatal "Can't get tag for last tag"
+
 		# set USEBRANCH
 		set_usebranch
 
@@ -132,9 +135,7 @@ if [ "$PKGVENDOR" = "alt" ] && is_gear $SPECDIR ; then
 			continue
 		fi
 
-		# TODO: check result message for merge?
-		# Use heads/ against warning: refname 'branch-name' is ambiguous
-		docmd git merge --no-ff heads/$CURBRANCH
+		docmd git merge --no-ff $LASTTAG
 
 		# override spec conflicts
 		mv -f $BPSPEC $SPEC || fatal
