gremote and ginit are out of the tool now

diff --git a/bin/rpmbs b/bin/rpmbs
--- a/bin/rpmbs
+++ b/bin/rpmbs
@@ -236,7 +236,7 @@ if [ -n "$UPLOADNOW" ] && is_gear $SPECDIR ; then
 	TAG=$(get_last_tag)
 
 	# TODO: add check for repo (as in rpmgp) and run ginit if needed
-	docmd $ETERBUILDBIN/gpush $GIRARHOST $FORCE || fatal "gpush failed. Possibly you need to run '\$ ginit $GIRARHOST' for create remote repo."
+	docmd gpush $GIRARHOST $FORCE || fatal "gpush failed. Possibly you need to run '\$ ginit $GIRARHOST' for create remote repo."
 	echo
 	echo "Run build $PROJECTNAME at $GIRARHOST"
 	if [ -n "$PREPARETASK" ] ; then
