rpmpub: rewrite check for target default, use BUILDFARMDIR from Korinf

diff --git a/bin/rpmpub b/bin/rpmpub
--- a/bin/rpmpub
+++ b/bin/rpmpub
@@ -11,6 +11,12 @@
 
 load_mod spec rpm etersoft
 
+# fast load Korinf config for BUILDFARMDIR
+test -f /etc/eterbuild/korinf && . /etc/eterbuild/korinf
+test -f $KORINFETC/korinf && . $KORINFETC/korinf
+test -f ~/.config/korinf  && . ~/.config/korinf
+
+
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 	echog "rpmpub - Etersoft specific script for publish gear repo to target ftp dir as src.rpm"
 	echog "Usage: rpmpub [-f] [-r PROJECTVERSION ] [SPEC] [TARGETDIR]"
@@ -57,20 +63,26 @@ if [ ! -r "$SPECNAME" ] ; then
 fi
 
 #Example: ETERDESTSRPM=/var/ftp/pub/Etersoft/CIFS@Etersoft/$VERSION/sources
-[ -n "$ETERDESTSRPM" ] || ETERDESTSRPM="$1"
+# config value by default
+ETERDESTSRPM=$BUILDFARMDIR
+
+# try override from value from spec
+tfs=$(get_etersoft_srpm_path $SPECNAME "$ALPHA")
+if [ -n "$tfs" ] ; then
+	ETERDESTSRPM="$tfs"
+fi
+#	[ -n "$ETERDESTSRPM" ] || fatal "Can't detect target dir from spec (Url in Source: field). Run rpmpub with TARGETDIR param"
+
+# override with command arg
+[ -n "$1" ] &&  ETERDESTSRPM="$1"
 
 # add sources if not yet
 if [ -n "$ETERDESTSRPM" ] && ! rhas "$ETERDESTSRPM" "/sources" ; then
 	ETERDESTSRPM=$ETERDESTSRPM/sources
 fi
 
-if [ -z "$ETERDESTSRPM" ] ; then
-	ETERDESTSRPM=$(get_etersoft_srpm_path $SPECNAME "$ALPHA")
-	[ -n "$ETERDESTSRPM" ] || fatal "Can't detect target dir from spec (Url in Source: field). Run rpmpub with TARGETDIR param"
-	echo "Prepare src.rpm to $ETERDESTSRPM"
-else
-	test -d "$ETERDESTSRPM" || fatal "You need run with exists dir to publish src.rpm project (I have checked $ETERDESTSRPM, it does not exist)"
-fi
+[ -d "$ETERDESTSRPM" ] || fatal "You need run with exists dir to publish src.rpm project (I have checked $ETERDESTSRPM, it does not exist)"
+echo "Prepare src.rpm to $ETERDESTSRPM"
 export ETERDESTSRPM
 
 PREVPATH=$(readlink -m "$ETERDESTSRPM/../../last")
