do not use docmd against loginhsh run (fix auto login to hasher after build)

diff --git a/bin/rpmrb b/bin/rpmrb
--- a/bin/rpmrb
+++ b/bin/rpmrb
@@ -51,5 +51,6 @@ if is_gear ; then
 	git_commit_ignore_nothing $SPEC -m "update spec to new build $(get_version $SPEC) (with rpmrb script)" || exit 1
 fi
 
-docmd $ETERBUILDBIN/rpmbsh -i $SPEC || fatal "Error with build in hasher"
+showcmd $ETERBUILDBIN/rpmbsh -i $SPEC
+$ETERBUILDBIN/rpmbsh -i $SPEC || fatal "Error with build in hasher"
 docmd $ETERBUILDBIN/rpmbs $GIRARHOST -u $SPEC || fatal "Error with upload"
