rpmrb: remove -r support

diff --git a/bin/rpmrb b/bin/rpmrb
--- a/bin/rpmrb
+++ b/bin/rpmrb
@@ -20,12 +20,6 @@ if [ "$1" = "-h" ]; then
 	exit 0
 fi
 
-REMOTE=
-if [ "$1" = "-r" ] ; then
-	REMOTE=$1
-	shift
-fi
-
 set_girar_host $1 && shift
 
 SPEC=$1
@@ -48,5 +42,5 @@ if is_gear ; then
 	git_commit_ignore_nothing $SPEC -m "update spec to new build $(get_version $SPEC) (with rpmrb script)" || exit 1
 fi
 
-docmd $ETERBUILDBIN/rpmbsh $REMOTE -i $SPEC || fatal "Error with build in hasher"
+docmd $ETERBUILDBIN/rpmbsh -i $SPEC || fatal "Error with build in hasher"
 docmd $ETERBUILDBIN/rpmbs $GIRARHOST -u $SPEC || fatal "Error with upload"
