fix files location

diff --git a/share/eterbuild/functions/common b/share/eterbuild/functions/common
--- a/share/eterbuild/functions/common
+++ b/share/eterbuild/functions/common
@@ -3,14 +3,24 @@
 # Author: Vitaly Lipatov <lav@etersoft.ru>
 # Public domain
 
-ETERBUILDETC=/etc/eterbuild
-ETERBUILDDIR=/usr/share/eterbuild
+set_eterbuilddir()
+{
+	# if run from no system installation
+	if dirname $0 | grep $ETERBUILDDIR >/dev/null ; then
+		ETERBUILDETC=/etc/eterbuild
+		ETERBUILDDIR=/usr/share/eterbuild
+	else
+		ETERBUILDDIR=$(realpath `dirname $0`/../share/eterbuild)
+		ETERBUILDETC=$(realpath `dirname $0`/../etc)
+		echo "Note: run from source tree, datadir=$ETERBUILDDIR, sysconfdir=$ETERBUILDETC"
+	fi
+}
 
-# if run from local installation
-if ! dirname $0 | grep /usr/share >/dev/null ; then
-	ETERBUILDDIR=$(realpath `dirname $0`/../share/eterbuild)
-	ETERBUILDETC=$(realpath `dirname $0`/../etc)
-	echo "Note: run from source tree, datadir=$ETERBUILDDIR, sysconfdir=$ETERBUILDETC"
+# set if empty and check it
+[ -n "$ETERBUILDDIR" ] || set_eterbuilddir
+if [ -z "$ETERBUILDIR" ] ; then
+	echo "Can't detect package files location"
+	exit 1
 fi
 
 # Выводит указанное сообщение об ошибке и завершает программу
