set_eterbuilddir: exit if the utils' source tree is not found

diff --git a/share/eterbuild/functions/common b/share/eterbuild/functions/common
--- a/share/eterbuild/functions/common
+++ b/share/eterbuild/functions/common
@@ -146,9 +146,8 @@ set_eterbuilddir()
 				echo "Note: run from source tree, datadir=$ETERBUILDDIR, sysconfdir=$ETERBUILDETC"
 			fi
 		else
-			warning "Cannot find source tree root in source tree mode"
-			ETERBUILDETC=/etc/eterbuild
-			ETERBUILDDIR=/usr/share/eterbuild
+			echo "Cannot find source tree root in source tree mode" >&2
+			exit 1
 		fi
 	fi
 	ETERBUILDBIN=$(realpath $ETERBUILDDIR/../../bin)
