use make_temp_file, some cleanups

diff --git a/share/eterbuild/functions/rpm b/share/eterbuild/functions/rpm
--- a/share/eterbuild/functions/rpm
+++ b/share/eterbuild/functions/rpm
@@ -73,25 +73,24 @@ build_rpms_name()
 	NAMESPEC=$1
 	shift
 	test -f "$NAMESPEC" || fatal "Spec $NAMESPEC does not exist"
-	# Check for broken mktemp
-	if mktemp -V &>/dev/null ; then
-		tmprpm=`mktemp || exit 1`
-	else
-		tmprpm=`mktemp /tmp/$NAME.XXXXXX || exit 1`
-	fi
+
+	tmprpm=`make_temp_file $NAME`
+	# Optimization
 	eval_spec $NAMESPEC $@ | grep ":"  >$tmprpm
-	CATSPEC="cat $tmprpm"
-	BASENAME=$($CATSPEC | get_var "Name")
-	RELEASE=$($CATSPEC | get_var "Release")
-	VERSION=$($CATSPEC | get_var "Version")
-	TARBALLNAME=$($CATSPEC | get_var "Source.*")
+	BASENAME=$(cat $tmprpm | get_var "Name")
+	RELEASE=$(cat $tmprpm | get_var "Release")
+	VERSION=$(cat $tmprpm | get_var "Version")
+	TARBALLNAME=$(cat $tmprpm | get_var "Source.*")
 	[ -n "$TARBALLNAME" ] && TARBALLNAME=$(basename $TARBALLNAME)
 	rm -f $tmprpm
+
 	NAMERPMIN=$BASENAME-$VERSION-$RELEASE.$DEFAULTARCH.rpm
 	NAMESRPMIN=$BASENAME-$VERSION-$RELEASE.src.rpm
 
 	#RPMSOURCEDIR=$RPMDIR/SOURCES
 	RPMSOURCEDIR=`rpm --eval %_sourcedir | subst_namever`
+	[ -n "$RPMSOURCEDIR" ] || fatal "Can't detect RPM/SOURCESd ir"
+
 	local BNS NSS
 	BNS="$BASENAME".spec
 	NSS=`basename $NAMESPEC`
