move share to share/eterbuild for compat with installed hierarhy add support for run from the source tree move helper files to eterbuild/functions break functions/common in small thematic files

diff --git a/etersoft-build-utils/share/eterbuild/functions/publish-compat b/etersoft-build-utils/share/eterbuild/functions/publish-compat
--- a/etersoft-build-utils/share/eterbuild/functions/publish-compat
+++ b/etersoft-build-utils/share/eterbuild/functions/publish-compat
@@ -114,3 +114,14 @@ publish_tarball()
 		ssh $PUBLICSERVER ln -sf $TARNAME $PUBLICPATH/$BASENAME-current.tar.bz2
 	fi
 }
+
+
+# Publish srpm (need ETERDESTSRPM)
+publish_srpm()
+{
+	echo "Copying $NAMESRPMIN to $ETERDESTSRPM"
+	export ETERDESTSRPM
+	rpmbs -s $* $SPECNAME || fatal "Can't build SRPMS"
+}
+
+
